// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// Protobuf Java Version: 3.25.3
package com.example.protobuf;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<com.example.protobuf.Student> 
      getStudentsList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.example.protobuf.Student getStudents(int index);
  /**
   * <code>repeated .Student students = 1;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<? extends com.example.protobuf.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.example.protobuf.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
